#Recording error for exception: <class 'Exception'>

#function: functools.partial(<function consume_iterable_in_list at 0x7e2f8445c550>, <function download_structure at 0x7e2f842d2950>, mmcif=False)

#signature: (*args, **kwargs)

#Args:

('PDBC', ['hain'])

#Kwargs:



#traceback:

Traceback (most recent call last):
  File "/home/cmcajsa/Documents/PhD_december2024/sa_discos/Automation_tool_scripts_MAHTI/Idpconfgenerator_automation/IDPConformerGenerator/src/idpconfgen/logger.py", line 112, in report_on_crash
    return func(*args, **kwargs)
  File "/home/cmcajsa/Documents/PhD_december2024/sa_discos/Automation_tool_scripts_MAHTI/Idpconfgenerator_automation/IDPConformerGenerator/src/idpconfgen/libs/libmulticore.py", line 28, in consume_iterable_in_list
    return list(func(*args, **kwargs))
  File "/home/cmcajsa/Documents/PhD_december2024/sa_discos/Automation_tool_scripts_MAHTI/Idpconfgenerator_automation/IDPConformerGenerator/src/idpconfgen/libs/libdownload.py", line 36, in download_structure
    downloaded_data, _ = fetch_pdb_id_from_RCSB(pdbname, mmcif=mmcif)
TypeError: cannot unpack non-iterable NoneType object


